pipeline {
    agent any

    tools {
        maven 'Maven_3_8_7'  // Replace 'Maven_3_8_7' with the name of your Maven installation in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[credentialsId: 'my-github-access-key', url: 'https://github.com/Bankofafrica-projetintegre/bmce-backend-with-pipline.git']]])
         	}
            }
        }
    
	

        stage('Compile') {
            steps {
                script {
                    sh "mvn clean install"
                }
            }
        }
        stage('Debug') {
            steps {
                script {
                    sh "ls -l target/"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
			        sh "docker logout"
                    // Build Docker image using the Dockerfile in your project
                    sh "docker build -t soulredouane/spring-bmce:2.0 ."
                }
            }
        }
       stage('Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-token', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh "echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin"
                }
            }
        }
        stage('Push') {
			steps {
				sh 'docker push soulredouane/spring-bmce:2.0'
				sh "docker logout"
			}
		}
    }
}