# Start with a base Java image
FROM openjdk:17-jdk-alpine

WORKDIR /app

# Make port 8081 available 
EXPOSE 15000

ADD target/server-0.0.1-SNAPSHOT.jar /app/bmce-ftp.jar

RUN mkdir -p /app/src/main/resources/static

# Execute the jar upon container startup 
ENTRYPOINT ["java", "-jar", "/app/bmce-ftp.jar"]